name = "nengo-master"
compatibility_date = "2025-12-27"
main = "src/index.tsx"

[vars]
HOST = "https://nengo-master.o-lab.workers.dev"
ENVIRONMENT = "production"

[assets]
binding = "ASSETS"
directory = "./src/public"
