name = "nengo-master"
compatibility_date = "2025-12-27"
main = "src/index.tsx"

[assets]
binding = "ASSETS"
directory = "./src/public"

[vars]
ENVIRONMENT = "production"
GOOGLE_ADSENSE_ID = "ca-pub-3860710971355910"
